version: "3.7"
services:

  app:
    build:
      args:
        user: cloudy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: porto-cloudy
    container_name: porto-app
    restart: unless-stopped
    ports:
      - 8000:80
    working_dir: /var/www/html/
    volumes:
      - ./storage/logs:/var/www/html/storage/logs
      - ./storage/app:/var/www/html/storage/app
    networks:
      - porto

  db:
    image: postgres:14
    container_name: porto-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - 5434:5432
    volumes:
      - ./docker-compose/postgres:/var/lib/postgresql/data
    networks:
      - porto

networks:
  porto:
    driver: bridge
